#!/usr/bin/env python3
"""Write results_table.tex and results_macros.tex from ../output/design_scan.csv.

Run from any directory: python3 co-evolution/report/make_table.py
"""
import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
rows = list(csv.DictReader((HERE.parent / 'output' / 'design_scan.csv').open()))
start_name = {'default': '(0.3, 0)', 'yielding': '(0.1, 1)'}

lines = [r'\begin{tabular}{rlcrrrrrrr}', r'\toprule',
         r'$\mu$ & start $(u_B,u_P)$ & conv. & $\Phi$ & $\int(b-h)^2$ & $\int(p-b)^2$ & '
         r'$c_P\!\int u_P^2$ & $\int u_B$ & $b(T)$ & $p(T)$\\', r'\midrule']
for r in rows:
    f = lambda k: f'{float(r[k]):.3f}'
    lines.append(f"{float(r['mu']):g} & {start_name[r['start']]} & "
                 f"{'yes' if r['converged'] == 'true' else 'no'} & {f('Phi')} & {f('health')} & "
                 f"{f('mismatch')} & {f('effort')} & {f('body_adaptation')} & {f('b_T')} & {f('p_T')}\\\\")
lines += [r'\bottomrule', r'\end{tabular}']
(HERE / 'results_table.tex').write_text('% Generated by make_table.py from ../output/design_scan.csv\n'
                                        + '\n'.join(lines) + '\n')

# Macros for the numbers quoted in the text (default start).
def pick(mu, start='default'):
    return next(r for r in rows if float(r['mu']) == mu and r['start'] == start)

macros = []
for name, mu in (('Zero', 0.0), ('One', 1.0)):
    r = pick(mu)
    for key, macro in (('Phi', 'Phi'), ('body_adaptation', 'Adapt'), ('b_T', 'bT'),
                       ('p_T', 'pT'), ('health', 'Health'), ('mismatch', 'Mismatch')):
        macros.append(rf'\newcommand{{\res{macro}{name}}}{{{float(r[key]):.2f}}}')
converged = sum(r['converged'] == 'true' for r in rows)
macros.append(rf'\newcommand{{\resSolves}}{{{len(rows)}}}')
macros.append(rf'\newcommand{{\resConverged}}{{{converged}}}')
(HERE / 'results_macros.tex').write_text('% Generated by make_table.py from ../output/design_scan.csv\n'
                                         + '\n'.join(macros) + '\n')
print(f'Wrote results_table.tex and results_macros.tex ({len(rows)} solves, {converged} converged)')
